### ISSUE TITLE
Error login in

### ISSUE THREAD

**Issue by charles-philippe** [nfarina/homebridge-tesla#2]
[Model S] Error logging into Tesla: Error: 401: {"response":"undefined_method_`strip'_for_nil:nilclass"}

any clues why I'm getting this error?

Thanks

**Comment by nfarina** [comment]
Hmm .. perhaps something to do with your account? I just now tried using Siri to check lock/unlock state and it logged in for me without issue.

That error is particular bizarre - speaks to a server problem on their end.

**Comment by OddArneRoll** [comment]
I have the same problem, on a "Rasberry Pi Nano Wireless" install. 
Everything works like a charm on my other x86 linux box.
But on my Pi nano, i get:
[Model S] Error logging into Tesla: Error: 401: {"response":"undefined_method_`strip'_for_nil:nilclass"}
-- Where do i go from here? 
Teslacmd works like it should, im able to get information from my car, also from my RasPi Nano...

**Comment by PeterBizz** [comment]
howdi, 
did you manage to find a solution? I am facing the same problem 
It happens when I try to retreive access token, using postman as testtool.  this is my request: 

POST /oauth/token HTTP/1.1
Host: owner-api.teslamotors.com
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache

grant_type=password&client_id=81527cff06843c8634fdc09e8ac0abefb46ac849f38fe1e431c2ef2106796384&client_secret=4034f9419ee651c7d0e5f7aa6bfbd18bafb5c5c033b093bb2fa3&username=emailofowner%40ownerdomain.xx&password=droopie

**Comment by OddArneRoll** [comment]
Yes, i configured the npm package homebridge-tesla to use username and password instead of token, i think that was the workaround that made the problem go away.

**Comment by PeterBizz** [comment]
thx, 
I have found the solution that gives me a working token: 

all example documentation of Get-Token uses **username**= , 
instead the request for the token should use **email**=
_Tools like Postman use username as well when Request Token is issued ( which fails)._

the full request is: 
POST /oauth/token HTTP/1.1
Host: owner-api.teslamotors.com
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache

grant_type=password&client_id=81527cff06843c8634fdc09e8ac0abefb46ac849f38fe1e431c2ef2106796384&client_secret=4034f9419ee651c7d0e5f7aa6bfbd18bafb5c5c033b093bb2fa3&email=emailofowner%40ownerdomain.xx&password=droopie

**Comment by cbrandlehner** [comment]
I think this issue can be closed as of current version fixing it.

**Comment by nfarina** [comment]
Thanks!
