### ISSUE TITLE
Is it possible to summon?

### ISSUE THREAD

**Issue by iainternet** [nfarina/homebridge-tesla#37]
It would be kinda cool to be able to ask Siri to get the car out of the garage :)

**Comment by nfarina** [comment]
That would indeed be cool 😎 I’m not sure what it would take, but would be happy to review a PR for it!

**Comment by focher** [comment]
It is very unlikely that summon can be added. Currently, the teslajs package doesn't include any summon related API support. I suspect that Tesla doesn't easily make that functionality available due to the risks it could create.

You can see the documented APIs that teslajs supports at https://www.npmjs.com/package/teslajs.

**Comment by focher** [comment]
This is simply impossible as Tesla doesn't expose the API to perform Summon. I recommend the issue be closed.

**Comment by iainternet** [comment]
I understand. Thanks for looking into.
