### ISSUE TITLE
Climate as HVAC accessory

### ISSUE THREAD

**Issue by eddydas** [nfarina/homebridge-tesla#48]
Great plug-in!

Have you considered exposing the climate as HVAC accessory rather than a plain switch? I’d love to be able to see the current interior temp and set target temp through HomeKit!

Thank you

**Comment by nfarina** [comment]
I’ve thought about it! But didn’t want to put in the work mostly. Also I wasn’t sure how useful it would be since the car has to be woken up to get data like current interior temp. The Tesla API is best for things like write-only switches since the car must be woken up first which takes time and costs car battery watts.

**Comment by eddydas** [comment]
I'm thinking the moment we care about the temperature inside is when we're using dog mode/camp mode etc, which the car will be awake already - wondering if it justifies that better!
But I'm also unsure whether making it an HVAC control will make HomeKit waking up the car every minute or so trying to get the temperature.

**Comment by nfarina** [comment]
Well, 2 years later, this is finally implemented in the beta version of the plugin :) If you're still using it I'd appreciate any feedback. `npm install --global homebridge-tesla@beta`
