### ISSUE TITLE
disable notifications

### ISSUE THREAD

**Issue by arolson101** [nfarina/homebridge-tesla#64]
I'd like an option to globally disable notifications.  I have the home app on a number of devices and don't care about notifications anywhere; I don't want to have to go into each one individually to disable notifications on each thing

**Comment by nfarina** [comment]
So Homebridge plugins can't really control notifications - But if you go into the Home app on your device, you should be able to turn them off there.

**Comment by arolson101** [comment]
If I understand what you’re saying, if you present a lock to HomeKit, if you tell it that it is now unlocked you have no control over whether it sends a notification about it?

Would it be possible to add a setting to disable the charge port?  I only want HomeKit to be able to start and stop climate.

Also, what does “Model S Connection” mean?  Why is it a tile?

**Comment by nfarina** [comment]
Correct, HomeKit accessories doesn't know anything about notifications. I believe iOS enables notifications for "secure" devices like locks and such by default, but it's not always reliable because many Homebridge plugins only bother querying state when asked explicitly by the user (or when the user visits the HomeKit UI on their device).

The "Model S Connection" tile is kind of a workaround - when Siri wants to know if your car doors are unlocked for instance, we won't go and wake up the car (which consumes battery) just to tell it the answer, because this can happen many times throughout the day. As a compromise, I created a "Connection" switch so you can explicitly "Turn on the Model S Connection" which wakes up the car, then you can ask if the doors are unlocked and get an accurate answer.

The plugin used to have lots of settings to enable/disable the various services but it got kind of unwieldy so now they're just all enabled. If you wanted to implement that again and send a PR I'd be happy to merge it though.
