### ISSUE TITLE
Add API token support

### ISSUE THREAD

**Issue by epheterson** [nfarina/homebridge-tesla#7]
Leaving a password in plaintext is undesirable, it’d be cool to support getting a token once with the credentials instead, either with the plugin itself or another site. TeslaFi vends these tokens and they can be obtained in other ways.

**Comment by nfarina** [comment]
So under the hood, the library logs into the Tesla API and receives an OAuth token which is stored and used for subsequent requests. We could have the user enter this token instead of a password, but ... I'm not sure it would be an improvement. The user would have to do this extra step of getting a token and pasting it into the config file, and ultimately it doesn't increase security, since having the token is exactly like having the password - you can unlock and start the car, etc.

That said, I do get the discomfort of having the password in plaintext - if you wanted to make a PR that adds the option for giving the token instead, I would be happy to merge. Note that the token may need to be periodically "refreshed" - I'm not sure how long the token we get right now will last before expiring. [More info here](https://github.com/mseminatore/TeslaJS/issues/74).
