### ISSUE TITLE
Lock Command opens Trunk

### ISSUE THREAD

**Issue by sdorilas** [nfarina/homebridge-tesla#73]
Hello there,

New user, recently installed. Plug-in is working exactly as expected, with one exception. Whenever I tell Siri “Lock my Model Y doors”. She will lock the doors but she will also open the Trunk. Is this a config issue?

**Comment by nfarina** [comment]
That is super strange, I haven't seen this before. Is it still happening?

**Comment by JBake130** [comment]
Just installed and only see one “switch” unlock, which opens my trunk as well

**Comment by krinderknecht** [comment]
Same. Also Model Y. Unlocking opens the trunk and frunk. Locking opens the trunk. :(

**Comment by kkissane0328** [comment]
New user, same issue here

**Comment by johnschult** [comment]
Same issue with my Model Y

**Comment by luke2m** [comment]
This is slightly different, here (Model Y) the trunk and frunk open when asking "unlock the model y doors". 

I think this is because Siri is recognizing anything configured as a lock as on a  door, so it is opening all of them. A workaround I have found is renaming "doors" to "car doors".
@nfarina It seems like if there could be a config option to present the frunk and trunk as a switch rather than a lock, as there is with Sentry mode, this could be solved.

**Comment by nfarina** [comment]
yeah I've been having this problem as well, not sure how to best remedy. I think renaming "doors" to "car doors" is a good interim solution.

Changing the trunk+frunk to be switches would mean that you would have to say "Turn on the trunk" which is a bit awkward.
