### ISSUE TITLE
Operation timed out error when using with Shortcuts

### ISSUE THREAD

**Issue by cantchooseaname8** [nfarina/homebridge-tesla#82]
Hi. This works great when using it directly through the Home app. However, I'm trying to set up a few shortcuts through the Shortcuts app. I have the first input set to turn the car connection on (i.e. wake up the car). However, this always results in a "Operation timed out" error when running this input through the Shortcuts app. Once that happens, the shortcut stops and doesn't move on to the next commands. I'm using the default setting of 1 minute in Homebridge to wait for the car to wake up. However, the operation timed out error pops up after only about 10 seconds. Is there something that I'm doing wrong?

**Comment by cantchooseaname8** [comment]
I was testing it out with just a simple command (i.e. unlocking the doors) to make sure it works before attempting to make it more complex. I'm wondering when that 1 minute setting in Homebridge to wake up the car actually comes into play. Maybe that's how long it will wait once the button is pressed within the Home app, but the Shortcuts app doesn't follow that approach?

**Comment by nfarina** [comment]
It's confusing for sure. The minute timeout is how long the plugin will wait for a response - but that's not related to HomeKit's behavior. Apple wants to provide a good user experience and they have determined that they can't wait longer than 10 seconds for anything.

Because of the nature of waking up these cars, it almost always takes longer than 10 seconds. So when Shortcuts tries to do anything with the car, it's likely going to time out, and that will result in Shortcuts proceeding with the assumption that it didn't work (even if the command eventually goes through).

**Comment by cantchooseaname8** [comment]
Thanks for the quick responses! It sucks how rigid Apple makes these things work. The homebridge plugin works flawlessly. It's just another example of Apple not playing nice. Thanks for all the work on this!

**Comment by nfarina** [comment]
This should be fixed in the beta version of the plugin!
